### ISSUE TITLE
Good idea, why doesnt exist yet? Are we doing it wrong?

### ISSUE THREAD

**Issue by emilebosch** [mdub/rspec-longrun#6]
Hi !
I supe feel the need for this! any idea why it doesnt exist yet? Are we doing it wrong (tm)

**Comment by mdub** [comment]
What do you need? What doesn't exist? What are you doing?

**Comment by emilebosch** [comment]
Well i am having the same issue. Long running cross role workflows selenium tests with Rspec. I am wondering why there isnt another way to or something embedded in order to report on user progress within a long running feature. Usually this means that i am either using it wrong. Or we're just the only ones having this issue. Do you use this in production?

**Comment by mdub** [comment]
Hey @emilebosch. Sorry, but I'm still confused. 

You opened a new issue here, so I'm unsure what you mean by "having the same issue". Are you having a problem using `rspec-longrun`?  Is it not working as advertised?  If not, please explain how you tried to use it, what you expected to see, and what you saw instead.

As for "not existing yet", well, `rspec-longrun` does exist, and does provide an way to "report on user progress within a long running feature".  For a quick demo, try checking out this project, then run

    bundle install
    bundle exec rspec examples

**Comment by emilebosch** [comment]
No what i am saying is. Why isnt this a part of the default RSPEC suite. The gem is good, the idea is good. But if we are the only one needing it, maybe we use RSPEC wrong? That's what i meant basically.

**Comment by mdub** [comment]
Ah, now I'm with you.  Good question. 

I suspect most RSpec users are using it for unit-tests, and that some would say that those of us using it for functional/acceptance tests are "doing it wrong".

I do reckon you're onto something - this should probably be built into RSpec, rather than monkey-patched in, as evidenced by issue#5.

However, since your question isn't an bug, as such, I'm going to close it.
